name: recipes
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_picker: ^0.6.1+10
  cloud_firestore: ^0.12.9+6
  font_awesome_flutter: ^8.5.0
  firebase_auth: ^0.14.0+5
  firebase_storage: ^3.0.6
  date_format: ^1.0.8
  intl: ^0.16.0
  modal_progress_hud: ^0.1.3
  intro_slider: ^2.2.8
  path_provider: ^1.4.0
  google_maps_flutter: ^0.5.21+8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/

